//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIPV17.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIPV17.Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;id-ID&quot;&gt;
        ///  &lt;Title Text=&quot;Sales Overview&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;ObjectDataSource ComponentName=&quot;dashboardObjectDataSource1&quot;&gt;
        ///      &lt;Name&gt;Object Data Source 1&lt;/Name&gt;
        ///      &lt;DataSource Type=&quot;DemoLibrary.BusinessObjects.Sales.SaleItem, DemoLibrary, Version=1.0.6448.33491, Culture=neutral, PublicKeyToken=null&quot; /&gt;
        ///    &lt;/ObjectDataSource&gt;
        ///  &lt;/DataSources&gt;
        ///  &lt;Items&gt;
        ///    &lt;Grid ComponentName=&quot;gridDashboardItem1&quot; Name=&quot;Sales by Category&quot; Data [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SalesOverview {
            get {
                return ResourceManager.GetString("SalesOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Dashboard CurrencyCulture=&quot;en-US&quot;&gt;
        ///  &lt;Title Text=&quot;Shipping Provinces&quot; /&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;ObjectDataSource ComponentName=&quot;dashboardObjectDataSource1&quot;&gt;
        ///      &lt;Name&gt;Object Data Source 1&lt;/Name&gt;
        ///      &lt;DataSource Type=&quot;DemoLibrary.BusinessObjects.Sales.SaleItem, DemoLibrary, Version=1.0.6448.33812, Culture=neutral, PublicKeyToken=null&quot; /&gt;
        ///    &lt;/ObjectDataSource&gt;
        ///  &lt;/DataSources&gt;
        ///  &lt;Items&gt;
        ///    &lt;RangeFilter ComponentName=&quot;rangeFilterDashboardItem1&quot; Name=&quot;Range [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShippingProvince {
            get {
                return ResourceManager.GetString("ShippingProvince", resourceCulture);
            }
        }
    }
}
